# db_input_fields = {
#     "Defect_ref_no": None,
#     "Date": None,
#     "Repeated_defect": None,
#     "Type_of_road": None,
#     "Location": None,
#     "Landmark": None,
#     "Type_of_asset": None,
#     "Description": None,
#     "Quantity": None,
#     "Measurement": None,
#     "Cause_of_defect": None,
#     "Recommendation": None,
#     "Inspected_by": None,
#     "Supervised_by": None,
#     "Reported_via__method": None,
#     "Reported_via__agency": None,
#     "Reported_via__date": None,
#     "Reported_via__time": None,
#     "Acknowledgement__method": None,
#     "Acknowledgement__date": None,
#     "Acknowledgement__time": None,
#     "Defects_verified_by__name": None,
#     "Defects_verified_by__date": None,
#     "Instructions": None,
#     "WSO_no": None,
#     "Acknowledged_and_received_by__name": None,
#     "Acknowledged_and_received_by__date": None,
# }

db_input_fields = (
    "Defect_ref_no",
    "Date",
    "Repeated_defect",
    "Type_of_road",
    "Location",
    "Landmark",
    "Type_of_asset",
    "Description",
    "Quantity",
    "Measurement",
    "Cause_of_defect",
    "Recommendation",
    "Inspected_by",
    "Supervised_by",
    "Reported_via__method",
    "Reported_via__agency",
    "Reported_via__date",
    "Reported_via__time",
    "Acknowledgement__method",
    "Acknowledgement__date",
    "Acknowledgement__time",
    # "Defects_verified_by__name",
    # "Defects_verified_by__date",
    # "Instructions",
    # "WSO_no",
    # "Acknowledged_and_received_by__name",
    # "Acknowledged_and_received_by__date",
)