# db_input_fields = {
#     "Defect_ref_no": None,
#     "Date": None,
#     "Repeated_defect": None,
#     "Type_of_road": None,
#     "Location": None,
#     "Landmark": None,
#     "Type_of_asset": None,
#     "Description": None,
#     "Quantity": None,
#     "Measurement": None,
#     "Cause_of_defect": None,
#     "Recommendation": None,
#     "Inspected_by": None,
#     "Supervised_by": None,
#     "Reported_via__method": None,
#     "Reported_via__agency": None,
#     "Reported_via__date": None,
#     "Reported_via__time": None,
#     "Acknowledgement__method": None,
#     "Acknowledgement__date": None,
#     "Acknowledgement__time": None,
#     "Defects_verified_by__name": None,
#     "Defects_verified_by__date": None,
#     "Instructions": None,
#     "WSO_no": None,
#     "Acknowledged_and_received_by__name": None,
#     "Acknowledged_and_received_by__date": None,
# }

db_input_fields = (
    "defect_ref_no",
    "date",
    "repeated_defect",
    "type_of_road",
    "location",
    "zone",
    "landmark",
    "type_of_asset",
    "description",
    "quantity",
    "measurement",
    "cause_of_defect",
    "recommendation",
    "inspected_by",
    "supervised_by"
)